In [1]:
# 1. Importando a biblioteca NumPy
import numpy as np

# 2. Criando array unidimensional de 1 a 10
arr = np.arange(1, 11)
print("Array arr:")
print(arr)

# 3. Criando matriz 3x4 de 1 a 12
matriz = np.arange(1, 13).reshape(3, 4)
print("\nMatriz 3x4:")
print(matriz)

# 5. Acessando elementos específicos
elemento_arr = arr[4]  # Índice 4 = 5º elemento (Python é 0-based)
elemento_matriz = matriz[1, 3]  # Linha 1, coluna 3 = 8
print(f"\nElemento '5' do arr: {elemento_arr}")
print(f"Elemento '8' da matriz: {elemento_matriz}")

# 6. Fatiamento do array (índices 2 a 6 exclusivo)
arr_slice = arr[2:6]
print("\nSlice do arr (índices 2-6):")
print(arr_slice)

# 7. Operação matemática (multiplicação por 2)
arr_resultado = arr * 2
print("\nArray arr multiplicado por 2:")
print(arr_resultado)

# 8. Soma dos elementos da matriz
soma_matriz = np.sum(matriz)
print(f"\nSoma da matriz: {soma_matriz}")

# 9. Média dos elementos do array
media_arr = np.mean(arr)
print(f"Média do arr: {media_arr:.2f}")  # .2f para 2 casas decimais

# 10. Matriz transposta
matriz_transposta = matriz.T
print("\nMatriz transposta:")
print(matriz_transposta)

# 11. Concatenando arrays
arr_concatenado = np.concatenate((arr, arr_slice))
print("\nArrays concatenados:")
print(arr_concatenado)

# 12. Resumo dos dados
print("\n=== Resumo Final ===")
print(f"Array original: {arr}")
print(f"Matriz original:\n{matriz}")
print(f"Soma da matriz: {soma_matriz}")
print(f"Média do array: {media_arr:.2f}")
print(f"Matriz transposta:\n{matriz_transposta}")
print(f"Arrays concatenados: {arr_concatenado}")

Array arr:
[ 1  2  3  4  5  6  7  8  9 10]

Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Elemento '5' do arr: 5
Elemento '8' da matriz: 8

Slice do arr (índices 2-6):
[3 4 5 6]

Array arr multiplicado por 2:
[ 2  4  6  8 10 12 14 16 18 20]

Soma da matriz: 78
Média do arr: 5.50

Matriz transposta:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Arrays concatenados:
[ 1  2  3  4  5  6  7  8  9 10  3  4  5  6]

=== Resumo Final ===
Array original: [ 1  2  3  4  5  6  7  8  9 10]
Matriz original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Soma da matriz: 78
Média do array: 5.50
Matriz transposta:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Arrays concatenados: [ 1  2  3  4  5  6  7  8  9 10  3  4  5  6]
